#!/usr/bin/env python3
"""Pack the rosco queue into site/js/data.js (base64, day-indexed from launch date)."""
import json, base64, glob

LAUNCH = '2026-09-21'   # day 0 = deploy day

def main():
    files = ['tools/raw/roscos.json'] + sorted(glob.glob('tools/raw/roscos-b*.json'))
    days = []
    for f in files:
        for ros in json.load(open(f, encoding='utf-8')):
            cells = [{'l': c['l'], 'm': c['mode'], 'q': c['g'], 'a': c['w']} for c in ros['cells']]
            days.append({'cells': cells})
    payload = json.dumps(days, ensure_ascii=False, separators=(',', ':')).encode('utf-8')
    b64 = base64.b64encode(payload).decode('ascii')
    out = ("// Generated by tools/genera_web.py - do not edit\n"
           f"const ROSCO_LAUNCH = '{LAUNCH}';\n"
           f"const ROSCO_DAYS_B64 = '{b64}';\n")
    open('site/js/data.js', 'w', encoding='utf-8').write(out)
    print(f'days packed: {len(days)} -> site/js/data.js ({len(b64)//1024} KB b64)')

if __name__ == '__main__':
    main()
